package com.irsspace.irs;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Location")
@org.kie.api.definition.type.Description("Location Class for Student, School and Office location information")
public class irsLocation implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Location Name")
	private java.lang.String name;
	@org.kie.api.definition.type.Label("Latitude")
	private java.lang.Double latitude;
	@org.kie.api.definition.type.Label("Longitude")
	private java.lang.Double longitude;
	public irsLocation() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.Double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(java.lang.Double latitude) {
		this.latitude = latitude;
	}

	public java.lang.Double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(java.lang.Double longitude) {
		this.longitude = longitude;
	}

	public irsLocation(java.lang.String name, java.lang.Double latitude,
			java.lang.Double longitude) {
		this.name = name;
		this.latitude = latitude;
		this.longitude = longitude;
	}
	
    public long getDistanceTo(irsLocation location) {
        // Implementation specified by TSPLIB http://www2.iwr.uni-heidelberg.de/groups/comopt/software/TSPLIB95/
        // Euclidean distance (Pythagorean theorem) - not correct when the surface is a sphere
        double latitudeDifference = location.latitude - latitude;
        double longitudeDifference = location.longitude - longitude;
        double distance = Math.sqrt(
            (latitudeDifference * latitudeDifference) + (longitudeDifference * longitudeDifference));
        return (long) (distance * 1000.0 + 0.5);
    }
	
	@Override
    public String toString() {
        if (name == null) {
            return super.toString();
        }
        return name;
    }

}