package com.irsspace.irs;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("irsSchool")
public class irsSchool implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Location")
	private com.irsspace.irs.irsLocation location;

	public irsSchool() {
	}

	public com.irsspace.irs.irsLocation getLocation() {
		return this.location;
	}

	public void setLocation(com.irsspace.irs.irsLocation location) {
		this.location = location;
	}

	public irsSchool(com.irsspace.irs.irsLocation location) {
		this.location = location;
	}

}