package com.irsspace.irs;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("School")
public class irsSchool implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Name of School")
	private java.lang.String name;
	@org.kie.api.definition.type.Label(value = "Location of School")
	private com.irsspace.irs.irsLocation location;

	public irsSchool() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public com.irsspace.irs.irsLocation getLocation() {
		return this.location;
	}

	public void setLocation(
			com.irsspace.irs.irsLocation location) {
		this.location = location;
	}

	public irsSchool(
			java.lang.String name,
			com.irsspace.irs.irsLocation location) {
		this.name = name;
		this.location = location;
	}

}