package com.irsspace.irs;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Vehicle")
public class irsVehicle implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Capacity of Vehicle")
	private int capacity;
	@org.kie.api.definition.type.Label(value = "irsOffice")
	private java.lang.String office;
	@org.kie.api.definition.type.Label(value = "Next Student to be picked-up or dropped for same Vehicle")
	private java.lang.String nextStudent;

	public irsVehicle() {
	}

	public int getCapacity() {
		return this.capacity;
	}

	public void setCapacity(int capacity) {
		this.capacity = capacity;
	}

	public java.lang.String getOffice() {
		return this.office;
	}

	public void setOffice(java.lang.String office) {
		this.office = office;
	}

	public java.lang.String getNextStudent() {
		return this.nextStudent;
	}

	public void setNextStudent(java.lang.String nextStudent) {
		this.nextStudent = nextStudent;
	}

	public irsVehicle(int capacity, java.lang.String office,
			java.lang.String nextStudent) {
		this.capacity = capacity;
		this.office = office;
		this.nextStudent = nextStudent;
	}

}