package com.irsspace.irs;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Vehicle")
public class irsVehicle implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Capacity of Vehicle")
	private int capacity;
	@org.kie.api.definition.type.Label("Next Student to be picked-up or dropped for same Vehicle")
	private irsStudent nextStudent;

	@org.kie.api.definition.type.Label(value = "Office Location")
	private com.irsspace.irs.irsLocation officeLocation;

	public irsVehicle() {
	}

	public int getCapacity() {
		return this.capacity;
	}

	public void setCapacity(int capacity) {
		this.capacity = capacity;
	}

	public com.irsspace.irs.irsLocation getOfficeLocation() {
		return this.officeLocation;
	}

	public void setOfficeLocation(com.irsspace.irs.irsLocation officeLocation) {
		this.officeLocation = officeLocation;
	}

	public com.irsspace.irs.irsStudent getNextStudent() {
		return this.nextStudent;
	}

	public void setNextStudent(com.irsspace.irs.irsStudent nextStudent) {
		this.nextStudent = nextStudent;
	}

	public irsVehicle(int capacity, com.irsspace.irs.irsStudent nextStudent,
			com.irsspace.irs.irsLocation officeLocation) {
		this.capacity = capacity;
		this.nextStudent = nextStudent;
		this.officeLocation = officeLocation;
	}

}